services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - .env

  dashboard:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8003
    depends_on:
      - api
